#!/bin/bash

MASTER_IP=${1}
MASTER_IP_LAST_OCTAL=${2}
NETWORK=${3}
WORKERS=${4}

TMP_HOSTS="/vagrant/shared/hosts"

echo -e "\n# generated by $0 - $(date)" > ${TMP_HOSTS}
echo "${MASTER_IP} k8s-master" >> ${TMP_HOSTS}

for i in `seq 1 ${WORKERS}` ; do
	echo "${NETWORK}.$(( ${MASTER_IP_LAST_OCTAL} + ${i})) k8s-worker-${i}" >> ${TMP_HOSTS}
done

echo -e "#\n" >> ${TMP_HOSTS}

cat ${TMP_HOSTS}
cat ${TMP_HOSTS} >> /etc/hosts

exit 0
